project:
  type: website

website:
  title: "Redes Neuronales Artificiales y Algoritmos Bioinspirados"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



